Mathsquareweb/Models/ErrorViewModel.cs
using System;

namespace Mathsquareweb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mathsquareweb/Controllers/CalController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mathsquareweb.Models;

namespace Mathsquareweb.Controllers
{
    public class CalController : Controller
    {
        [HttpGet]
        public ActionResult add()
        {
            return View();
        }

        [HttpPost]
        
        public ActionResult add(string firstnumb, string secondnumb)
        {
            // this section accept the number entered by the users and the processing continues
            double numbone = int.Parse(firstnumb);
            double numbtwo = int.Parse(secondnumb);

            if(numbone < 0 || numbtwo < 0){
               string result = "You entered a negative number. \nPlease enter postive number.";
               ViewBag.result = result;
            }else{
                numbone = Math.Sqrt(int.Parse(firstnumb));
                numbtwo = Math.Sqrt(int.Parse(secondnumb));

                if(numbone > numbtwo){
                    string result = "Ok! " + numbone + " Is your first number root greater than your second number root " + numbtwo;
                    ViewBag.result = result;
                }else if(numbone == numbtwo){
                    string result = "Please enter another numbers the two roots are equal " + numbone + " and " + numbtwo;
                    ViewBag.result = result;
                }else{
                    string result = "Ok! " + numbtwo + " Is your second number root greater than your first number root " + numbone;
                    ViewBag.result = result;
                }; // end second if statement
                
                
            };//end first if statement
            
            return View();
        }
    }
}

Mathsquareweb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mathsquareweb.Models;

namespace Mathsquareweb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Csharpweb()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mathsquareweb/Views/Cal/add.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3 class="display-4">This page tells you which is the greater between two digits entered </h3>
    <h4>So enter a valid number greater that zero else boom on your screen. <br /> Good luck!!! </h4>
    
</div>

<!--This is to receive input from the user.-->
<div style="text-align:center;">
    <form asp-controller="Cal" asp-action="add" method="POST">
        <input type="number" placeholder = "firstnumber" name="firstnumb" />
        <input type="number" placeholder = "secondnumber" name="secondnumb" />
        <input type="submit" value="submit" />
         
    </form>
    
</div>
<p></p>

<!--This is to display the user result.-->
<div style="text-align:center;">
@{
    if(ViewBag.result != null){
    <p>
        <strong><h3>You just got this from what you entered<br /></h3></strong>
        <strong>@ViewBag.result</strong>
    </p>
    }
}
</div>

Mathsquareweb/Views/Home/Csharpweb.cshtml
@{
    ViewData["Title"] = "Csharp web page";
}
<h1>@ViewData["Title"]</h1>

<p>This is my first csharp web page created. That's cool.</p>

Mathsquareweb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mathsquareweb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mathsquareweb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mathsquareweb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Mathsquareweb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>